version: '3.7'

services:

  waiter:
    container_name: rmap-waiter
    build:
      context: ./
      dockerfile: docker/Dockerfile.waiter

  redis:
    container_name: rmap-redis
    image: redis:6.0
    command: redis-server --requirepass REconDIS
    ports:
      - 6379:6379
    volumes:
      - ./data-redis:/data

  mysql:
    container_name: rmap-mysql
    image: quay.io/reconmap/rest-api-db:latest
    build:
      context: ./
      dockerfile: docker/mysql/Dockerfile
    volumes:
      - ./data-mysql:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: reconmuppet
      MYSQL_DATABASE: reconmap
      MYSQL_USER: reconmapper
      MYSQL_PASSWORD: reconmapped

  api:
    container_name: rmap-api
    image: quay.io/reconmap/rest-api:latest
    build:
      context: ./
      dockerfile: docker/api/Dockerfile
    volumes:
      - "./config.json:/var/www/webapp/config.json"
      - "./logs:/var/www/webapp/logs"
      - "./data:/var/www/webapp/data"
      - "./composer.json:/var/www/webapp/composer.json"
      - "./composer.lock:/var/www/webapp/composer.lock"
      - "./vendor:/var/www/webapp/vendor"
      - "./public:/var/www/webapp/public"
      - "./docs/openapi.yaml:/var/www/webapp/public/docs/openapi.yaml"
      - "./docs/schemas/:/var/www/webapp/public/docs/schemas/"
      - "./src:/var/www/webapp/src"
      - "./resources:/var/www/webapp/resources"
      - "./tests:/var/www/webapp/tests"
      - "./phpunit.xml.dist:/var/www/webapp/phpunit.xml.dist"
      - "./run-tests.sh:/var/www/webapp/run-tests.sh"
    ports:
      - 8080:80
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_USER: default
      REDIS_PASSWORD: REconDIS

  wss:
    container_name: rmap-wss
    image: quay.io/reconmap/ws-server:latest
    ports:
      - 4040:8765
    environment:
      VALID_ORIGINS: http://localhost:3001
      REDIS_HOST: redis://redis
      REDIS_PASSWORD: REconDIS

