type: object
required:
  - name
  - description
  - visibility
properties:
  id:
    type: integer
  name:
    type: string
  description:
    type: string
  visibility:
    type: string
  archived:
    type: boolean
