openapi: 3.0.3

info:
  title: Reconmap API
  description: Reconmap API documentation
  version: 0.9.0

servers:
  - url: 'http://localhost:3000'
  - url: 'https://api.reconmap.org'

components:

  securitySchemes:

    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:

    Attachment:
      type: object
      required:
        - client_file_name
      properties:
        id:
          type: integer
        client_file_name:
          type: string
        file_size:
          type: integer
        file_mimetype:
          type: string
        file_hash:
          type: string

    Organisation:
      type: object
      required:
        - name
      properties:
        id:
          type: integer
        name:
          type: string
        url:
          type: string
        contactName:
          type: string
        contactEmail:
          type: string
        contactPhone:
          type: string

    Client:
      type: object
      required:
        - name
        - contactName
        - contactEmail
      properties:
        id:
          type: integer
        name:
          type: string
        url:
          type: string
        contactName:
          type: string
        contactEmail:
          type: string
        contactPhone:
          type: string

    Command:
      type: object
      required:
        - short_name
        - docker_image
        - arguments
      properties:
        id:
          type: integer
        short_name:
          type: string
        docker_image:
          type: string
        arguments:
          type: string

    User:
      type: object
      required:
        - name
        - password
        - email
        - role
      properties:
        id:
          type: integer
        name:
          type: string
        password:
          type: string
        email:
          type: string
        role:
          type: string

    Target:
      type: object
      required:
        - projectId
        - name
        - kind
      properties:
        id:
          type: integer
        projectId:
          type: integer
        name:
          type: string
        kind:
          type: string

    Vulnerability:
      type: object
      required:
        - summary
        - description
        - risk
        - status
        - substatus
      properties:
        id:
          type: integer
        summary:
          type: string
        description:
          type: string
        risk:
          type: string
        status:
          type: string
        substatus:
          type: string

security:
  - BearerAuth: [ ]

paths:

  ### Audit log ###

  /auditlog:
    get:
      tags:
        - Audit log
      security:
        - BearerAuth: [ ]
      responses:
        '200':
          description: OK

  /attachments:
    post:
      tags:
        - Attachments
      security:
        - BearerAuth: [ ]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Attachment'
      responses:
        '200':
          description: Attachment succesfully created response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Attachment'
    get:
      tags:
        - Attachments
      security:
        - BearerAuth: [ ]
      responses:
        '200':
          description: OK
  '/attachments/{id}':
    get:
      tags:
        - Attachments
      parameters:
        - name: id
          in: path
          description: Attachment ID
          required: true
          schema:
            type: integer
            format: int64
      security:
        - BearerAuth: [ ]
      responses:
        '200':
          description: Succesfully retrieved
    delete:
      tags:
        - Attachments
      parameters:
        - name: id
          in: path
          description: Attachment ID
          required: true
          schema:
            type: integer
            format: int64
      security:
        - BearerAuth: [ ]
      responses:
        '200':
          description: Succesfully deleted

  /clients:
    post:
      tags:
        - Clients
      security:
        - BearerAuth: [ ]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Client'
      responses:
        '200':
          description: Client succesfully created response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Client'
    get:
      tags:
        - Clients
      security:
        - BearerAuth: [ ]
      responses:
        '200':
          description: OK
  '/clients/{id}':
    get:
      tags:
        - Clients
      parameters:
        - name: id
          in: path
          description: Client ID
          required: true
          schema:
            type: integer
            format: int64
      security:
        - BearerAuth: [ ]
      responses:
        '200':
          description: Succesfully retrieved
    delete:
      tags:
        - Clients
      parameters:
        - name: id
          in: path
          description: Client ID
          required: true
          schema:
            type: integer
            format: int64
      security:
        - BearerAuth: [ ]
      responses:
        '200':
          description: Succesfully deleted

  ### Projects ###

  /projects:
    get:
      tags:
        - Projects
      security:
        - BearerAuth: [ ]
      responses:
        '200':
          description: OK
  '/projects/{id}':
    get:
      tags:
        - Projects
      parameters:
        - name: id
          in: path
          description: Project ID
          required: true
          schema:
            type: integer
            format: int64
      security:
        - BearerAuth: [ ]
      responses:
        '200':
          description: Succesfully retrieved
    delete:
      tags:
        - Projects
      parameters:
        - name: id
          in: path
          description: Project ID
          required: true
          schema:
            type: integer
            format: int64
      security:
        - BearerAuth: [ ]
      responses:
        '200':
          description: Succesfully deleted

  ### Reports ###

  /reports:
    get:
      tags:
        - Reports
      security:
        - BearerAuth: [ ]
      responses:
        '200':
          description: OK

  ### Targets ###

  /targets:
    post:
      tags:
        - Targets
      security:
        - BearerAuth: [ ]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Target'
      responses:
        '201':
          description: Target succesfully created response
          content:
            application/json:
              schema:
                type: object
                properties:
                  username:
                    type: string
                  password:
                    type: string
  '/targets/{id}':
    get:
      tags:
        - Targets
      parameters:
        - name: id
          in: path
          description: Target ID
          required: true
          schema:
            type: integer
            format: int64
      security:
        - BearerAuth: [ ]
      responses:
        '200':
          description: Succesfully retrieved
    delete:
      tags:
        - Targets
      parameters:
        - name: id
          in: path
          description: Target ID
          required: true
          schema:
            type: integer
            format: int64
      security:
        - BearerAuth: [ ]
      responses:
        '200':
          description: Succesfully deleted

  ### Tasks ###

  /tasks:
    get:
      tags:
        - Tasks
      security:
        - BearerAuth: [ ]
      responses:
        '200':
          description: OK
  '/tasks/{id}':
    get:
      tags:
        - Tasks
      parameters:
        - name: id
          in: path
          description: Task ID
          required: true
          schema:
            type: integer
            format: int64
      security:
        - BearerAuth: [ ]
      responses:
        '200':
          description: Succesfully retrieved
    delete:
      tags:
        - Tasks
      parameters:
        - name: id
          in: path
          description: Task ID
          required: true
          schema:
            type: integer
            format: int64
      security:
        - BearerAuth: [ ]
      responses:
        '200':
          description: Succesfully deleted

  ### Users ###

  /users/login:
    post:
      tags:
        - Users
      security: [ ]
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
              required:
                - username
                - password
      responses:
        '200':
          description: Succesful login response
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
        '403':
          description: Unsuccesful login response
  /users:
    get:
      tags:
        - Users
      security:
        - BearerAuth: [ ]
      responses:
        '200':
          description: Succesful login response
          content:
            application/json:
              schema:
                type: object
                properties:
                  username:
                    type: string
                  password:
                    type: string
    post:
      tags:
        - Users
      security:
        - BearerAuth: [ ]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '200':
          description: User succesfully created response
          content:
            application/json:
              schema:
                type: object
                properties:
                  username:
                    type: string
                  password:
                    type: string
  '/users/{id}':
    get:
      tags:
        - Users
      parameters:
        - name: id
          in: path
          description: User ID
          required: true
          schema:
            type: integer
            format: int64
      security:
        - BearerAuth: [ ]
      responses:
        '200':
          description: Succesful login response
          content:
            application/json:
              schema:
                type: object
                properties:
                  username:
                    type: string
                  password:
                    type: string
    delete:
      tags:
        - Users
      parameters:
        - name: id
          in: path
          description: User ID
          required: true
          schema:
            type: integer
            format: int64
      security:
        - BearerAuth: [ ]
      responses:
        '200':
          description: Succesfully deleted

  ### Vulnerabilities ###

  /vulnerabilities:
    get:
      tags:
        - Vulnerabilities
      security:
        - BearerAuth: [ ]
      responses:
        '200':
          description: OK
    post:
      tags:
        - Vulnerabilities
      security:
        - BearerAuth: [ ]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Vulnerability'
      responses:
        '201':
          description: Vulnerability succesfully created response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Vulnerability'
  '/vulnerabilities/{id}':
    get:
      tags:
        - Vulnerabilities
      parameters:
        - name: id
          in: path
          description: Vulnerability ID
          required: true
          schema:
            type: integer
            format: int64
      security:
        - BearerAuth: [ ]
      responses:
        '200':
          description: Succesfully retrieved
    delete:
      tags:
        - Vulnerabilities
      parameters:
        - name: id
          in: path
          description: Vulnerability ID
          required: true
          schema:
            type: integer
            format: int64
      security:
        - BearerAuth: [ ]
      responses:
        '200':
          description: Succesfully deleted

  ### Organisations ###

  /organisations/root:
    put:
      description: "Updates the root organisation"
      tags:
        - Organisations
      security:
        - BearerAuth: [ ]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Organisation'
      responses:
        '200':
          description: Organisation succesfully created response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Organisation'
    get:
      tags:
        - Organisations
      security:
        - BearerAuth: [ ]
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Organisation'

  /commands:
    post:
      tags:
        - Commands
      security:
        - BearerAuth: [ ]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Command'
      responses:
        '200':
          description: Command succesfully created response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Command'
    get:
      tags:
        - Commands
      security:
        - BearerAuth: [ ]
      responses:
        '200':
          description: OK
  '/commands/{id}':
    get:
      tags:
        - Commands
      parameters:
        - name: id
          in: path
          description: Command ID
          required: true
          schema:
            type: integer
            format: int64
      security:
        - BearerAuth: [ ]
      responses:
        '200':
          description: Succesfully retrieved
    delete:
      tags:
        - Commands
      parameters:
        - name: id
          in: path
          description: Command ID
          required: true
          schema:
            type: integer
            format: int64
      security:
        - BearerAuth: [ ]
      responses:
        '200':
          description: Succesfully deleted

  /system/usage:
    get:
      tags:
        - System
      security:
        - BearerAuth: [ ]
      responses:
        '200':
          description: OK

  /system/data:
    get:
      tags:
        - System
      security:
        - BearerAuth: [ ]
      responses:
        '200':
          description: OK

  /integrations:
    get:
      tags:
        - System
      security:
        - BearerAuth: [ ]
      responses:
        '200':
          description: OK
